### ISSUE TITLE
Error while activating GUI.

### ISSUE THREAD

**Issue by hatakeyama-poke** [MaxReimann/video-stream-consistency#1]
A message indicated "The given version [13] is not supported, only version 1 to 10 is supported in this build.". Which version this message says? GUI can be Opened, but does not work.

**Comment by MaxReimann** [comment]
Which OS are you on? It sounds like a onnxruntime issue, perhaps its being loaded from your system onnxruntime?
Check if this https://github.com/microsoft/onnxruntime/issues/13606 helps (copying onnxruntime.dlls to the executable dir)

**Comment by hatakeyama-poke** [comment]
Thank you for reaction! By copying onnxruntime.dlls to the executable dir, I could resolve this error.
